### ISSUE TITLE
Gradle build instead of multi module maven project

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#107]
I think it would be a great idea to move to Gradle instead of using Maven :-)

**Comment by LarsEckart** [comment]
I could have a look at this :)

**Comment by JohannesLichtenberger** [comment]
No, a gradle multi project would be great, as you say. More or less the Maven stuff ported (once tried this for a big big monolith and was so frustrated and gave up, because I was and still am new to gradle... and the project at work is simply too big). However, I think SirixDB is rather small.

BTW: I had some trouble with the mvn release plugin and now I get a release in about 30 minutes instead of 4 hours or something like that :-D hope that would work with Gradle, too.

And sometimes I think if it's worth the work switching to Gradle? But all in all I think it's a win and I like it much more instead of this bloated XML configuration.

**Comment by JohannesLichtenberger** [comment]
BTW: this monolith has ANT build scripts ;-)

**Comment by LarsEckart** [comment]
Can you clarify, what is the sirix-cluster folder/modle doing right now? All I see is an empty Main.scala file.

**Comment by JohannesLichtenberger** [comment]
Nothing, I will delete it completely...

**Comment by LarsEckart** [comment]
I made a PR so that my progress is visible, guess that will make collaboration/discussions easier.

**Comment by JohannesLichtenberger** [comment]
Thank you so so much :-)

**Comment by JohannesLichtenberger** [comment]
Hey, I temporarily removed the Gradle stuff, as I thought it causes test case errors (turned out it was another test case bug somehow only happening during a specific order of tests on Travis and not locally). However, Travis also executed a Gradle specific thing, so I'm waiting ;-)

**Comment by JohannesLichtenberger** [comment]
Are you still working on this? :-)

**Comment by JohannesLichtenberger** [comment]
@LarsEckart guess, you haven't got any time, lately to work on this? But thanks a lot for the work you did already :+1:

**Comment by balajiv113** [comment]
Hi @JohannesLichtenberger, is this still up ?? I would like to work on this.

**Comment by JohannesLichtenberger** [comment]
@balajiv113 Still up. Lars has made a PR, which you take as a starting point if you like to :-)

I'd also love to use Quarkus for the REST-API bundle/module, but I should open another issue for this :-)

**Comment by JohannesLichtenberger** [comment]
This is done :-)
