### ISSUE TITLE
Test Setup of REST-API and running the integration tests

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#119]
The documentation can be found here: https://sirix.io/rest-api.html

**Comment by har-vy** [comment]
Hi @JohannesLichtenberger, this is my first issue, can I contribute?

**Comment by JohannesLichtenberger** [comment]
Yes, for sure :+1:

**Comment by JohannesLichtenberger** [comment]
@har-vy I think this will help a lot :-)

**Comment by har-vy** [comment]
@JohannesLichtenberger I have trouble building the project using Docker. There seems to be a persistent error "Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project sirix-core: Fatal error compiling: error: release version 13 not supported". Any idea how to remove this?

**Comment by JohannesLichtenberger** [comment]
Ah, you need the rather brand new Maven version: 3.6.2

**Comment by har-vy** [comment]
I installed Maven 3.6.2, the problem still remains

**Comment by JohannesLichtenberger** [comment]
Ah, we just changed to Java 13... I changed the Dockerfile minimally, maybe now?

**Comment by har-vy** [comment]
Thanks for the fixes, the server is up and running so is the keycloak. While running the tests there was a consistent error "io.vertx.core.VertxException: ALPN not available for JDK SSL/TLS engine" and the fix for that was to add a dependency for "io.netty:netty-tcnative-boringssl-static" in the pom.xml file. The error got removed and I tried to run the integration tests but even the first test doesn't finish running and it has been over 6-7 minutes. What should I do next

**Comment by JohannesLichtenberger** [comment]
Hmm, I only ever ran the tests within IntelliJ and started Keycloak without Docker. But I suppose that at least Keycloak and the SirixDB HTTP-Server are running without any problems? :-)

**Comment by har-vy** [comment]
Yeah the servers are up. I tried running tests through IntelliJ but it kept giving me the error port 9443 busy.

**Comment by JohannesLichtenberger** [comment]
Hmm

`johannes@johannesl3:~/sirixdb/sirix$ sudo docker-compose up server
sirix_keycloak_1 is up-to-date
Recreating sirix_server_1 ... done
Attaching to sirix_server_1
server_1           | io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8080
server_1           | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
server_1           | 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:579)
server_1           | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:820)
server_1           | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)`

**Comment by JohannesLichtenberger** [comment]
Need to figure out why the SirixDB HTTP-Server can't connect with Keycloak

**Comment by JohannesLichtenberger** [comment]
In `sirix-conf.json` change the Keycloak URL to `keycloak:8080` instead of `localhost:8080`:

```bash
johannes@johannesl3:~/sirixdb/sirix$ sudo docker-compose run --rm waitforkeycloak
Starting sirix_keycloak_1 ... done
Waiting for keycloak to listen on 8080...
sleeping
sleeping
sleeping
johannes@johannesl3:~/sirixdb/sirix$ sudo docker-compose up -d server
sirix_keycloak_1 is up-to-date
Starting sirix_server_1 ... done
```

And in a browser for instance: `https://localhost:9443/`. You'll get the Error from the SirixDB HTTP-Server: `Failure calling the RESTful API: token must not be null`.

**Comment by JohannesLichtenberger** [comment]
Hmmm, I hope this helped!? :-)

**Comment by yiss** [comment]
I suggest to use TestContainer so that we don't have to spin a docker container localy everytime we have to run integration tests :
https://github.com/cremich/testcontainers-keycloak this an example of using TestContainer with Keycloak

**Comment by JohannesLichtenberger** [comment]
That would be great, also especially regarding CI/CD... would you like to work on this? I'm not having much spare time currently (but would like to push the frontend a little bit forward). And next week "unfortunately" I'm in holidays for a week :-)

BTW: I updated the realm to "sirixdb" instead of master (if you run into problems currently).

**Comment by JohannesLichtenberger** [comment]
@yiss: Did you use this TestContainer before? Can you open another issue, such that it doesn't get lost? :+1:

**Comment by yiss** [comment]
@JohannesLichtenberger Yeah I've already used it on a project but I've never used it with Ketcloak. I'll create an issue for it

**Comment by JohannesLichtenberger** [comment]
Thank you :-)

**Comment by balajiv113** [comment]
@JohannesLichtenberger  
This has been covered and completed under PR #186
I think we can close this improvement, Unless there are some more changes planned.

**Comment by JohannesLichtenberger** [comment]
No, you're right :-)
