### ISSUE TITLE
Kotlin / a navigational concurrent axis

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#121]
Instead of blocking threads as in our current `ConcurrentAxis` (ExecutorService using a single thread pool and a BlockingQueue) and derivates we could implement Coroutine based axis which wrap normal axis using Coroutines/Channels.

**Comment by marcinbieleckiLLL** [comment]
Hey, from some time I want to take part in Sirix.
Can I work on this issue?

**Comment by JohannesLichtenberger** [comment]
Sure, any help is more than welcome :-) I'd put this in a sirix-kotlin module I guess.

**Comment by marcinbieleckiLLL** [comment]
You mean, that we should prefetch child nodes when we fetch parent node and on next iteration 
only collect already fetched child nodes?

So for example in DescendantAxis in nextKey method on first iteration should run 
asynchronous task which will produce child keys?

**Comment by JohannesLichtenberger** [comment]
When navigating down in the tree the right sibling nodes are stored in a Stack / Deque. They could for instance already be fetched in parallel within another operating system thread. I'm however now sure how many concurrent and parallel I/O can be done on modern SSDs or even way faster on byte addressable non-volatile storage as for instance Intel Opthane memory.

**Comment by JohannesLichtenberger** [comment]
Also as you mentioned probably first child or right siblings (the latter for leaf nodes).

However, I'm not sure to which extend this makes sense, as most nodes probably will be located on the same page but that depends on update modifications.

I guess in a first step paralellizing as in the ConcurrentAxis would be great, but non-blocking should probably hopefully be faster.

**Comment by marcinbieleckiLLL** [comment]
Okay, I think I understand :)
Didn't notice this Stack.

So same situation with Right Stack is in DescendantAxis and JsonDescendantAxis.

But there are also other axis which use stack:
- LevelOrderAxis - we could process all levels parallel?
- PrecedingAxis, FollowingAxis - process subtrees parallel?

But this require lot of changes I think. Just the idea.

**Comment by JohannesLichtenberger** [comment]
I think we'd also first have to research how much parallelization makes sense even on modern hardware. I'd love to work on a memory mapped I/O subsystem with the new foreign memory API and to make full use of for instance Intel Optane Memory, as SirixDB due to its log-structured persistent data-structure needs fast random access on non-volatile storage.

I'm currently working on fetching the page-fragments in parallel to restore a page in-memory as the sliding snapshot trails revisions of database data pages over several revisions (thus it stores the results of modifications plus some additional nodes).

**Comment by marcinbieleckiLLL** [comment]
Okay, so this for later, good luck with your task and have a nice weekend ;)

**Comment by JohannesLichtenberger** [comment]
Thanks, let me know if you work on the Concurrent Coroutines based axis :-)

**Comment by marcinbieleckiLLL** [comment]
Yes yes, I did it and now trying to do DescendantAxis to get rid of this right stack. 
Also need to setup Keycloak I think because I have exception during rest-api compose up, 
so will take some time for sure

**Comment by JohannesLichtenberger** [comment]
Did you push your stuff somewhere?

**Comment by marcinbieleckiLLL** [comment]
No, should I push this Coroutine axis?

**Comment by JohannesLichtenberger** [comment]
Maybe in your fork first. Do you have test cases?

**Comment by marcinbieleckiLLL** [comment]
Ok, I copied tests from ConcurrentAxis.

Do you have any branch naming rules? Can't find it anywhere.

**Comment by JohannesLichtenberger** [comment]
No, don't have any rules, that's up to you. Did you put this stuff in a new bundle/module?

For instance sirix-kotlin-api would be great.

**Comment by marcinbieleckiLLL** [comment]
Yes, there is sirix-kotlin-api
I raised pull request: https://github.com/sirixdb/sirix/pull/237

Also I have a question about DescendantAxis, we want to process right page of tree in parallel with left page, so it means that we need to do it more or less in same time, left page in main thread and right in coroutine. To do this we need two different instance of cursor or some locks and a lot of cursor position manipulation. NodeCursor is an interface so to clone it need to make some changes in all implementations (also I heard that clonning is generally bad practice), on the other hand don't know if there is any point to use coroutines with locks.

What do you think about it? Maybe there is other way to resolve it

**Comment by JohannesLichtenberger** [comment]
There's the resource manager.

`try (final var database = Databases.openJsonDatabase(databaseFile);
     final var manager = database.openResourceManager("resource");
     // Now open a read-only transaction again on the most recent revision.
     final var rtx = manager.beginNodeReadOnlyTrx()) { ... }`

I'd probably pass the resource manager to the axis. However, you have to make sure to close all opened read-only transactions in a close-method from the `AutoClosable` interface.

**Comment by marcinbieleckiLLL** [comment]
Ok, thanks :)

**Comment by marcinbieleckiLLL** [comment]
Hi, I made CoroutineDescendantAxis, but I've tested it and it is much slower than normal DescendantAxis.
I've made pull request but it isn't finished yet. Only want to know your thoughts about it :)

**Comment by JohannesLichtenberger** [comment]
I guess you might have a SATA drive. The SSD should be connected via a PCIe bus, otherwise it can not read in parallel I think.

Furthermore, it might be that most nodes are on the same node page / `UnorderedKeyValuePage` and thus it's already read during sequential access and synchronization overhead dominates.

**Comment by JohannesLichtenberger** [comment]
BTW: If you like we could think about a Kotlin DSL (but you might be more familiar with Kotlin :-)) or a Client for our REST-API would be great, to simplify working with SirixDB.

**Comment by marcinbieleckiLLL** [comment]
Don't know much about kotlin :)

You mean https://github.com/sirixdb/sirix-kotlin-client ?
Do you have any documentation?

**Comment by mosheduminer** [comment]
About documentation for the rest API - there is https://sirix.io/rest-api.html, though I think there might be some details there that weren't updated.
You can also use [the python client](https://github.com/sirixdb/sirix-python-client) for reference. There is also the [typescript/javascript client](https://github.com/sirixdb/sirix-typescript-client), but it's a bit of a mess and not very modular. I believe the python client is missing an endpoint or two, the typescript client has all the endpoints though, I think.
(I wrote those two clients, as well as a [dart client](https://github.com/mosheduminer/sirix-dart-client)) that is not in an official repo right now. If you have any questions about them, I can try to assist).

**Comment by marcinbieleckiLLL** [comment]
Sounds good. I can try to do it, but it will take some time for sure, because I have also other projects. Is there any deadline?

**Comment by mosheduminer** [comment]
No deadline, I would say. We would like to have a 1.0.0 release sooner rather than later, but maybe @JohannesLichtenberger has some timeline. There is a [roadmap](https://github.com/sirixdb/sirix/blob/master/ROADMAP.md) however. (The roadmap only references the vue/nuxt web frontend, but I've been working on https://github.com/sirixdb/sirix-svelte-front-end, though I've been busy of late, unfortunately).

**Comment by marcinbieleckiLLL** [comment]
Thought again about this task and I can't do it. 
I would do this with pleasure, because project is great 
but have some other projects with deadlines and don't have much time now :(

Sorry for the confusion.

**Comment by JohannesLichtenberger** [comment]
No problem 👍 I'm also working in my spare time on the project, because I really think it can be a great addition to the database systems world :-)
