### ISSUE TITLE
Fixing Javadoc

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#125]
In general we need to fix the Javadoc in the whole project (doclint).

**Comment by sneha122** [comment]
Hey I would like to work on this issue..
Could you assign it to me?

**Comment by JohannesLichtenberger** [comment]
Thanks a lot :-)

**Comment by Surya97** [comment]
Hey, can I work on this?

**Comment by JohannesLichtenberger** [comment]
@sneha122 working on it or can I reassign? Or you split the work, hmm :-)

**Comment by Surya97** [comment]
@sneha122 So, you are working on this issue or shall I take it over?

**Comment by sneha122** [comment]
@Surya97 you can take it over.... I am sorry for the delayed response

**Comment by JohannesLichtenberger** [comment]
@Surya97 guess you might not have time or as #Hacktoberfest is over, hmm

**Comment by punit-kulal** [comment]
hey, I would like to work on this issue, is the javadoc currently deployed anywhere, I couldn't find one

**Comment by JohannesLichtenberger** [comment]
Hm no, as of now it's not deployed

**Comment by punit-kulal** [comment]
I have started working on this, you can this issue to me, there are instances where the method signatures have changed. I have started to mark some todos there so that @JohannesLichtenberger  could look into it and think what the right value for that would be

**Comment by punit-kulal** [comment]
I have fixed all the errors of doclint barring references to class name that have probably been renamed or removed: Here's the list
org.ByteHandler.io.bytepipe.IByteHandler
QName
IVistor
IPage

**Comment by JohannesLichtenberger** [comment]
Can you make a PR? :+1:

**Comment by JohannesLichtenberger** [comment]
org.sirix.io.bytepipe.ByteHandler
org.brackit.xquery.atomic.QNm
org.sirix.api.visitor.NodeVisitor
org.sirix.page.interfaces.Page

**Comment by punit-kulal** [comment]
We can close this now
