### ISSUE TITLE
Use TestContainers for integration tests

### ISSUE THREAD

**Issue by yiss** [sirixdb/sirix#128]
The problem now is that when running integration tests we need to have a instance if keycloak running (the documentation shows how to run it using Dokcer)

Ideally we want to run integration tests without having to rely on having an instance of Keyloak running. To achieve that we would like to use TestContainers (official documentation : https://www.testcontainers.org/) to run Keycloak

Some other resources that may help : 
  - https://www.7p-group.com/blog/integrationstests-mit-testcontainers-spring-security-und-keycloak/
  - https://github.com/cremich/testcontainers-keycloak

@JohannesLichtenberger Can you export realm-export.json ?

**Comment by JohannesLichtenberger** [comment]
A realm export can be found here:

https://github.com/sirixdb/sirix/blob/master/bundles/sirix-rest-api/src/test/resources/realm-export.json

Thanks for adding this issue :-)

**Comment by JohannesLichtenberger** [comment]
Another resource (in german however):

https://www.7p-group.com/blog/integrationstests-mit-testcontainers-spring-security-und-keycloak/

**Comment by kulovan** [comment]
Hi, can I jump on this issue?

**Comment by balajiv113** [comment]
@JohannesLichtenberger 
Is this still up ? I could see a reverted commit in log.

**Comment by JohannesLichtenberger** [comment]
Hmm, maybe we can run the docker container via travis and add a user with the appropriate roles afterwards.

**Comment by yiss** [comment]
I've started working on it, while ago, hadn't had the chance to finish it. If you want I can give you a lead on what I've already did

**Comment by JohannesLichtenberger** [comment]
@yiss I reverted my changes regarding TestContainers, because I think starting a Keycloak container plus adding a user with the rights can be simply done via Travis:

https://docs.travis-ci.com/user/docker/

**Comment by balajiv113** [comment]
@JohannesLichtenberger we could also run docker image via gradle before test and after test we can stop the container

https://github.com/bmuschko/gradle-docker-plugin

**Comment by yiss** [comment]
@JohannesLichtenberger yeah that is more elegant implementation, maybe add the @balajiv113 suggestion too so that other contributers don't have to configure manually docker with keykloack
