### ISSUE TITLE
GET /{database} endpoint hangs

### ISSUE THREAD

**Issue by mosheduminer** [sirixdb/sirix#216]
**Describe the bug**
According to the [docs](https://sirix.io/rest-api.html#read), calling the `GET https://localhost:9443/<database>` endpoint should return the database name and its resources.
However, when I make a call to this endpoint, the request hangs, instead of receiving a response.

**To Reproduce**
I don't have yet have code in the sirix client libraries that call this endpoint (but I would like to add it, which is why I am now testing this endpoint). However, a call to this endpoint could be made with slight modifications (such as the getInfo function of the Database class in the typescript client).

**Expected behavior**
I expected a response from the endpoint.

**Comment by mosheduminer** [comment]
[sirix-data.zip](https://github.com/sirixdb/sirix/files/4231555/sirix-data.zip)
Here is the state of my sirix-data.

**Comment by JohannesLichtenberger** [comment]
Should be fixed now :-)
