### ISSUE TITLE
Error executing query through the REST-API

### ISSUE THREAD

**Issue by mosheduminer** [sirixdb/sirix#233]
**Describe the bug**
I sent the following query to the /{database}/{resource} GET endpoint as the query parameter in the URL:
```xquery
let $values := bit:array-values(['bla', 0, true, null])\n return $values
```

The response was:
`Failure calling the RESTful API: class org.brackit.xquery.expr.SequenceExpr$EvalSequence cannot be cast to class org.brackit.xquery.xdm.Item (org.brackit.xquery.expr.SequenceExpr$EvalSequence and org.brackit.xquery.xdm.Item are in unnamed module of loader 'app')`.

**Comment by JohannesLichtenberger** [comment]
```xquery
let $array := ['bla', 0, true(), jn:null()]
for $value in $array
return $value
```

Should work now :-)
