### ISSUE TITLE
JsonNodeTrx / insert nodes as left sibling

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#255]
Inserting nodes as a left sibling should be possible for convenience.

**Comment by rbhatmanjunath** [comment]
Hi, can I work on this one?

**Comment by JohannesLichtenberger** [comment]
Sure :-)

**Comment by JohannesLichtenberger** [comment]
@rbhatmanjunath how is it going? Do you need help? :)

**Comment by JohannesLichtenberger** [comment]
@rbhatmanjunath, let me know if you still like to work on this, please.
