### ISSUE TITLE
JsonNodeTrx: Implement replaceNode operation

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#259]
We should be able to replace a node in a single atomic method. That way we can replace a value of an object key without having to remove the object key node and the value node and insert the same object key node again together with another value node.

**Comment by rbhatmanjunath** [comment]
Hi @JohannesLichtenberger. Can I work on this?

**Comment by JohannesLichtenberger** [comment]
Hi, sorry I forgot to close this issue, as I implemented this like two weeks ago: https://github.com/sirixdb/sirix/blob/627fa5a57a302b04d7165aad75a780d74e14c2e9/bundles/sirix-core/src/main/java/org/sirix/api/json/JsonNodeTrx.java#L20

However, there are plenty of other issues :+1:

**Comment by rbhatmanjunath** [comment]
okay :)
