### ISSUE TITLE
Replace the hash function

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#269]
We optionally store a rolling hash of all nodes in a resource. Currently, to avoid collisions as much as possible SirixDB uses the first 128 Bits of a 256 Bit SHA256 hash. We probably can use a non-cryptographic fast(er) hash function which produces a low number of hash colissions given 64Bit unique, dense, ascending nodeKeys + values...

**Comment by parameswaranmarimuthu** [comment]
Hi @JohannesLichtenberger , could you please share additional information on this? I can help you on this.

**Comment by JohannesLichtenberger** [comment]
@parameswaranmarimuthu sorry, I forgot to answer. Still interested? We want a hash function, which does not produce a collision with another node hash, but in contrast to cryptographic hash functions it should be very fast.

**Comment by parameswaranmarimuthu** [comment]
Yeah, sure. I can pick it up.
