### ISSUE TITLE
Improve query based updates/inserts

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#283]
Insertion of a subtree should be done without first materializing/serializing the item to add.

https://github.com/sirixdb/sirix/blob/master/bundles/sirix-xquery/src/main/java/org/sirix/xquery/json/JsonItemSequence.java

**Comment by ashish3805** [comment]
Hi @JohannesLichtenberger  can I take this one? Also, I may need little clarification I guess.

**Comment by JohannesLichtenberger** [comment]
The problem is, that the items are first serialized to a JSON string and the shreddered / imported into SirixDB. Analogous to the `JsonShredder` we'd need an `ItemShredder` or something like that to directly add the items to the SirixDB resource instead of the intermediate step of first serializing to JSON and then shredding into the SirixDB resource.

**Comment by JohannesLichtenberger** [comment]
It's used for updating queries (have a look into `JsonIntegrationTest`). The `insert into`... queries. First in-memory instances of the items are created. Afterwards, based on these items the SirixDB resource is going to be updated.

**Comment by ashish3805** [comment]
@JohannesLichtenberger I am unable to understand most of the domain. Can you point me to any doc that can help me understand the basic data models and flows? The integration did helped me a little in understanding the flow. What does a shredder do?
