### ISSUE TITLE
Add rewrite rules for names, that is field accesses

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#285]
We should add rewrite rules for index accesses if name indexes are applicable and no CAS or Path indexes are applicable. We should check for the leaf nodes first and internally rewrite the child based path to a parent based path sequence.

**Comment by YuraTy** [comment]
Good day.  I want to contribute to the development, but I have little experience in this, please tell me where I can start?

**Comment by JohannesLichtenberger** [comment]
Hi @YuraTy, actually I can close this issue, as I've implemented it some time ago.

The AST is traversed and appropriate child chains of deref nodes are searched and replaced through a single `IndexExpr` AST node which fetches the appropriate nodes at runtime.

https://github.com/sirixdb/sirix/blob/master/bundles/sirix-xquery/src/main/java/org/sirix/xquery/compiler/optimizer/walker/json/JsonObjectKeyNameStep.java

https://github.com/sirixdb/sirix/blob/master/bundles/sirix-xquery/src/main/java/org/sirix/xquery/compiler/expression/IndexExpr.java

Regarding CAS indexes we however just scratched the surface and only rewrite simple predicates with no more than one condition.
