### ISSUE TITLE
Insert lastChildPointer for JsonNodeTrx at least

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#294]
Thus, we can provide efficient insertions into objects (always at the last position) as well as avoid triggering of relabeling DeweyIDs.

**Comment by Raj-Datta-Manohar** [comment]
Hi @JohannesLichtenberger , I am new here and trying to work on this issue.  
I am stuck here at https://github.com/sirixdb/sirix/blob/81bdaaaf7931cdf9651e9b502c16df63b0274b53/bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeTrxImpl.java#L1616

trying to figure out if there will be a condition when inserting as Last Child similar to
https://github.com/sirixdb/sirix/blob/81bdaaaf7931cdf9651e9b502c16df63b0274b53/bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeTrxImpl.java#L1627-L1629

Would be great if you could help!!

**Comment by JohannesLichtenberger** [comment]
Whenever a node has no right sibling I'd say, the parent must be adapted. Furthermore if a node during deletes has no right siblings the parent must be adapted.

**Comment by JohannesLichtenberger** [comment]
For the current tree-encoding: https://www.baeldung.com/sirix#tree-encoding-in-sirix

**Comment by Raj-Datta-Manohar** [comment]
@JohannesLichtenberger, Could you help me out in the implementation of `insertValue(...)` method for inserting an ObjectRecord as Last Child  
As of now, the `insertValue(...)` method, https://github.com/sirixdb/sirix/blob/81bdaaaf7931cdf9651e9b502c16df63b0274b53/bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeTrxImpl.java#L581
always inserts as the first child,  
  
So I guess I need to implement a new method `insertValueForLastChild(...)`?

**Comment by JohannesLichtenberger** [comment]
@Raj-Datta-Manohar, that's a method internally used for inserting a value for a key or field (synonyms). That is, basically you only have a first child pointer and for the value a parent pointer (even though the parent pointer could be even omitted, strictly speaking just for convencience).

That is, the first child is also the last child, regarding the pointers.

**Comment by Raj-Datta-Manohar** [comment]
Thanks for the clarification @JohannesLichtenberger , I will raise a PR

**Comment by JohannesLichtenberger** [comment]
Thanks a lot, that's fast :-)

**Comment by JohannesLichtenberger** [comment]
We should also avoid storing the pointer twice in the case of an object field to child.

**Comment by JohannesLichtenberger** [comment]
You also have to adapt the nodes itself and the serialization/deserialization thereof. Have a look at `NodeKind`.

Can you also add some unit and/or integration tests? We have to increase our test coverage :-)

**Comment by Raj-Datta-Manohar** [comment]
I totally forgot about the serialize, deserialize, I'm writing them now.  
  
I will try to add some tests too:-)

**Comment by Raj-Datta-Manohar** [comment]
@JohannesLichtenberger , is there a reason for implementing last child only for Json and why not Xml?

**Comment by JohannesLichtenberger** [comment]
The reason is fast inserts into objects: https://github.com/sirixdb/sirix/issues/294#issuecomment-664904320

I'm not sure if it adds a lot of performance to queries, hm.

**Comment by JohannesLichtenberger** [comment]
BTW: If you like to you can join the Slack channel. However, I think today I might not be too active anymore (it's 10pm over here).

**Comment by Raj-Datta-Manohar** [comment]
@JohannesLichtenberger , why did you use `insertPos` instead of `insertPosition` here:  
https://github.com/sirixdb/sirix/blob/c556048afc67570567261c4c1cb813240f8fbb6f/bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeTrxImpl.java#L1648

**Comment by JohannesLichtenberger** [comment]
The parameter is not even used. I just removed it.

**Comment by JohannesLichtenberger** [comment]
Do you need more help?

**Comment by Raj-Datta-Manohar** [comment]
No, I have been busy, will work on the issue in day or two.  
Btw I'm also working on #255

**Comment by JohannesLichtenberger** [comment]
Ah, thanks :-) BTW: I think when you're finished we should refactor the `JsonNodeTrx` class and use a bunch of command delegates. I think it's way too long, even now without the additional methods. Furthermore we could use Dagger2 for compile time dependency injection, such that we can easily write unit tests. As of now most tests are rather integration tests (which might be also a good thing as we can change the internals much more easily).
