### ISSUE TITLE
Queries using the REST-API do not have proper authorization checks

### ISSUE THREAD

**Issue by mosheduminer** [sirixdb/sirix#319]
**Describe the bug**
It is possible for a user with only `view` permissions to access the databases using any query, even if that query modifes database state. This should be allowed only according to the `create` `delete` `modify` permissions granted to the user.

**To Reproduce**
You can create a new user with `view` permissions in keycloak, and then use the frontend to run an replace query.

**Expected behavior**
Capabilities of user should be limited by permissions, even when using queries.

**Comment by JohannesLichtenberger** [comment]
I think it's not that trivial, as we have to push down the OAuth2Auth handler (Keycloak) and the User. I'm not sure if we have to add wrapper objects everywhere to get these two parameters in `XmlDBNode` and the `JsonDBItem` implementations. If we check in a special `XQuery` class, we would have to parse the AST to get the database names, for the databases, which are touched by update queries.

**Comment by mosheduminer** [comment]
I suppose this issue can be closed now?

**Comment by JohannesLichtenberger** [comment]
It works only with the store wide roles (`view`, `modify`, `delete`...), but not with `dbname-view` and so on. O'd like to keep it open. So far I haven't been successful in delegating everything and adding new classes.

**Comment by JohannesLichtenberger** [comment]
Should be implemented now...
