### ISSUE TITLE
Add a compile time DI framework

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#343]
We should add a compile time framework (Dagger2?) to make it easier to mock dependencies of a class.

**Comment by SameerKhurana** [comment]
Hi Johannes,

I would like to work on the issue, Can you please share the project details.

Thanks,
Sameer

**Comment by Gabitchov** [comment]
Hello,

Is it still relevant?

**Comment by JohannesLichtenberger** [comment]
Yes, sure :-)

**Comment by JPDSousa** [comment]
Hey @JohannesLichtenberger 

Do you have a plan for this in mind? I did walkthrough at the code (mostly sirix-core), and this looks like an interesting challenge! If you haven't thought about this much so far, let me share some of my experience in past DI related challenges:

1. Get right of as many static state/methods as possible, as static dependencies go against injected dependencies. This might affect the API (based on the examples in the repo), which introduces a tradeoff;
2. Identify dependencies, which usually results in a lot of refactor patches;
3. Introduce the DI framework (ironically, this is usually the easiest part in my experience).

**Comment by JohannesLichtenberger** [comment]
I haven't thought about it in depth, but I think it would be great especially for future refactoring work (splitting the `NodeTrx` implementations / adding dedicated classes for insertions/updates/deletes...) and then in order to simply mock dependencies of units for unit tests.

However, I'm not entirely sure if in depth unit testing would be a great thing or if it would make refactorings harder, as in my experience most work has to be done, when the test code has to change due to production code changes. I think IIRC the DuckDB guys said that they are doing intensive integration tests to test modules or even whole queries because of that. But clearly you'll have a lot of edge cases, where it's better to do unit tests to find bugs early and not due to extensive debugging.

So, I'm for sure open to ideas and I agree that adding the DI-framework itself might be the simplest part.

**Comment by JPDSousa** [comment]
Alright 👍 

I'm gonna try to pick this up by first finding some low hanging fruit for static references or state that can be injected (based on your suggestions). Hopefully that will allow me to progress to point 2. Do you think I should link future PRs to this issue or do you prefer to have 1 refactor per github issue?

**Comment by JohannesLichtenberger** [comment]
I think the static references might hopefully be only used for static helper methods, which have no state or internally to set JVM instance wide variables (`Databases` for instance is the main entry point to create, open and delete databases). But for instance I wanted to omit factories for instance when we introduce `InsertionCommand`, `UpdateCommand`, `DeletionCommand` as dependencies of `JsonNodeTrxImpl`. Thanks a lot, it's great to get some help, as I'm the only one working on the core in my spare time :-)

**Comment by JohannesLichtenberger** [comment]
I think you can create separate issues and link the PRs to these issues 👍
