### ISSUE TITLE
Feature Request - sdb:path(...) xquery function

### ISSUE THREAD

**Issue by mosheduminer** [sirixdb/sirix#373]
### Feature idea

It should be possible to retrieve the path in the resource tree to a particular node. This will be useful for the frontend in https://github.com/sirixdb/sirix-svelte-frontend/issues/258, so that the path to a diff may be determined even if the node it is relevant to is not yet loaded (due to lazy loading).

**Comment by JohannesLichtenberger** [comment]
This is implemented as:

`sdb:path($doc as xs:structured-item) as xs:string` so you'd get something like `/foo/bar/@baz` for `<foo><bar baz="ddd"/></foo>` or `/foo/bar` for `{"foo": {"bar":true}}` or `/foo/[]/bar` for `{"foo": [{"bar":true}]` IIRC.

**Comment by mosheduminer** [comment]
@JohannesLichtenberger if I'm not mistaken, the problem with that is that there is no indexing for json arrays. `/foo/[0]/baz` would be needed for the frontend use-case.

**Comment by JohannesLichtenberger** [comment]
Ah, thanks for the reminder.

**Comment by JohannesLichtenberger** [comment]
It's now implemented :-)
