### ISSUE TITLE
Fix Sonar issues

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#440]
https://sonarcloud.io/summary/overall?id=sirixdb_sirix

**Comment by gvdutra** [comment]
Hello @JohannesLichtenberger Can I work on this? I am available to fix a few sonar issues. thanks.

**Comment by JohannesLichtenberger** [comment]
Of course :-)

**Comment by slashgk** [comment]
Hi @JohannesLichtenberger Raised a PR: https://github.com/sirixdb/sirix/pull/545

**Comment by slashgk** [comment]
Hi @JohannesLichtenberger 
Raised a PR: https://github.com/sirixdb/sirix/pull/667

**Comment by persy97** [comment]
Hi @JohannesLichtenberger
Raised a PR: https://github.com/sirixdb/sirix/pull/669

**Comment by JohannesLichtenberger** [comment]
@persy97 that's not enough for a meaningful contribution, sorry

**Comment by persy97** [comment]
@JohannesLichtenberger Pushed some more sonar fixes in the same PR. Please take a look.

**Comment by JohannesLichtenberger** [comment]
Thanks, but I think a cast is missing :)

**Comment by persy97** [comment]
Can you trigger the build again?

**Comment by Naman0133** [comment]
Hi @JohannesLichtenberger raised a PR: [#671](https://github.com/sirixdb/sirix/pull/671)

**Comment by Salonimalhotra** [comment]
Hi @JohannesLichtenberger raised a PR: https://github.com/sirixdb/sirix/pull/674
can someone from maintainer approve?

**Comment by smirti-barnwal** [comment]
Hi @JohannesLichtenberger raised a PR: https://github.com/sirixdb/sirix/pull/676
can someone from maintainer approve?
