### ISSUE TITLE
Allow setting (monotonically increasing) timestamps explicitly

### ISSUE THREAD

**Issue by mosheduminer** [sirixdb/sirix#447]
### Feature

Currently all timestamps are set by the system. We should make it possible to configure a resource to allow setting the timestamp explicitly (so long as it is later than the previous timestamp).

### Motivation

This will allow replication data from another database to a SirixDB instance, enabling the use of SirixDB as an secondary (analytics) databse.

### Suggested API

For resource creation, the creation functions in xquery, as well as the PUT /<database>/<resource> endpoint should accept a timestamp parameter.

For updates, the `sdb:commit()` function should optionally accept a timestamp for the commit. For autocommits, a query parameter provided in the rest api could be sufficient, but it would be preferable to be able to do this purely within xquery, even when autocommit is enabled. Finally, the POST /<database>/<resource> endpoint should have an optional timestamp parameter.

**Comment by mosheduminer** [comment]
It might be useful to throw an error if the explicit timestamp is in the future, as this would usually indicate a user error.

**Comment by JohannesLichtenberger** [comment]
It's possible with the exception of the create XQuery functions, as they internally use a Store which can be implemented by other systems besides SirixDB and I think this is a special case. But if really needed of course we could add methods in the interface in Brackit.
