### ISSUE TITLE
Adding optional request parameter "prettyPrint=true/false"

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#49]
For the RESTful-API it would be useful to have a prettyPrint=true/false parameter, if the XML-content 
HTTP-response body should be pretty printed or not.

**Comment by nkmurthy** [comment]
@JohannesLichtenberger i am new to opensource contribution can i work on this

**Comment by JohannesLichtenberger** [comment]
Yes, sure :-)

**Comment by jtsa0267** [comment]
Hi, I'm new to open source contribution as well. It seems like this issue is still open? If so, can I try to work on this?

**Comment by ciphx** [comment]
Is this issue still open? (Seems so from the list) And if yes, would it be fine if I picked it up? I am not sure if there has been some collab on it already.
Please let me know..

**Comment by JohannesLichtenberger** [comment]
Sure, thanks :)

**Comment by ciphx** [comment]
Hello,
what would be the starting point to look through? So that I can get a little context and start with the issue.

**Comment by JohannesLichtenberger** [comment]
@ciphx it's in the sirix-rest-api bundle. And there as of now restricted to binary XML data, as I haven't implemented the pretty printing of JSON resources as of now. I'll probably add another issue, as it's also a good first issue I think :-)

You'll find the appropriate locations in the class `org.sirix.rest.crud.xml.XmlGet`. And the location for the pretty printing is in the method `serializeResource`, a simple builder method (`prettyPrint()`).

**Comment by JohannesLichtenberger** [comment]
It would be nice to have an end-to-end test in `org.sirix.rest.SirixVerticleXmlTest`. I think you should be able to run the SirixDB server with Keycloak already set up with an admin user, which has all necessary roles assigned via `docker-compose`. `sudo docker-compose up`. Otherwise I hope you'll find the information in the [documentation](https://sirix.io/rest-api.html). Let me know if you need further help.

**Comment by ciphx** [comment]
I am trying to setup docker, fairly new to it, so will probably read up on docker and proceed. Aim is to get the server up by tonight(IST) and then come back with questions/update. Thanks for the prompt responses. :)
