### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#51]
As the RESTful-API and thus the docker container is needing a started Keycloak instance, we could provide a Docker Compose file.

**Comment by kmjayadeep** [comment]
Can I take this up?

**Comment by JohannesLichtenberger** [comment]
Sure, thank you :-)

Maybe you can talk to @anmonteiro, he found an issue (I think he might have added Keycloak already, but I'm not sure :)):
https://github.com/sirixdb/sirix/issues/100
