### ISSUE TITLE
Update Vert.x to newest version

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#517]
Some stuff has been deprecated, so it might not be that trivial, but I guess it should also be a good first issue.

**Comment by tsufiyan** [comment]
Can I work on this? if yes please assign

**Comment by JohannesLichtenberger** [comment]
Sure, thanks

**Comment by tsufiyan** [comment]
Hi @JohannesLichtenberger
Should this issue be closed?
