### ISSUE TITLE
`sirix-benchmarks` bundle currently not working

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#521]
We should enable the bundle again and get it working thus that we can add much more benchmarks.

**Comment by akhil9281** [comment]
Hello @JohannesLichtenberger, I am new here, can you please elaborate the issue?

**Comment by JohannesLichtenberger** [comment]
The tests are currently not even found. But I think it would be better to copy the code in a new repository instead of a module and use Maven instead of Gradle (I guess it's the preferred way).
