### ISSUE TITLE
Update to Java19

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#534]
Update SirixDB to Java19.

**Comment by haseeb-xd** [comment]
I want to do this. I just need to make sure that i only have to update the version in pom.xml file right?

**Comment by JohannesLichtenberger** [comment]
No, actually in the gradles build file plus maybe API changes from the Foreign Memory API, changing the Github Action, the Dockerfile...

**Comment by alky003** [comment]
Hi @JohannesLichtenberger  this is my first time contributing could you please tell me exactly what I have to do?
thanks.

**Comment by ganeshannt** [comment]
hey @alky003  below PR changes may help you to do this one 
https://github.com/sirixdb/sirix/issues/534

**Comment by fMurugi** [comment]
Hi I would like to work on this.

**Comment by artwo** [comment]
Hey @JohannesLichtenberger please also consider me to contribute to this issue if @this-Aditya is not able to do it ;)

**Comment by JohannesLichtenberger** [comment]
@this-Aditya should @artwo work on the task? I'd probably like to try virtual threads for parallel I/O.

**Comment by artwo** [comment]
Please give it time while I work in the other issue.

**Comment by this-Aditya** [comment]
Ya sure
