### ISSUE TITLE
Make sirix server wait untill keycloak is completely up and running when using docker compose

### ISSUE THREAD

**Issue by redwanulsourav** [sirixdb/sirix#549]
The Sirix server depends on Keycloak for authentication. It takes a while for the Keycloak server to be up and running when using `docker compose`. The server throws exception trying to access Keycloak, and keeps on restarting. The server should not be started until Keycloak is completely up and running.

This is not specifically a bug, but it could be considered as an improvement.

**Comment by JohannesLichtenberger** [comment]
Regarding Keycloak, I'm also not sure if we can switch to a newer version. I think at one point they more or less completely rewrote Keycloak for faster startup times? I'm not sure, though... will have to check.
