### ISSUE TITLE
Slow hashing

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#572]
We should replace SHA256 to 128 bit truncated hashes for the nodes to XXHash, which is extremely fast: https://github.com/OpenHFT/Zero-Allocation-Hashing

**Comment by JohannesLichtenberger** [comment]
We have to change `AbstractNodeHashing` to use long-values and a 64bit XXHash for instance. Furthermore, we have to change all nodes (in the `org.sirix.node`-package).

Then, we have to adapt a few serialization test cases (for the new generated hashes, as well as a python client test IIRC).

**Comment by kamalanarayan91** [comment]
Hi! I'd like to take a crack at this.  Please let me know any further details.

**Comment by JohannesLichtenberger** [comment]
Hi Kamal, I've already switched to the new approach locally, but something is still off, as the new approach is still about 2- 2,5x slower. I'm not really sure, as the method in question for adding the hashes has very low CPU consumption (looking at the async profiler flame graph output). Tomorrow/later on I'll add two JFR recordings from the profiler (with and without hashes).

**Comment by JohannesLichtenberger** [comment]
The recordings: [jfr-recordings.tar.gz](https://github.com/sirixdb/sirix/files/10531359/jfr-recordings.tar.gz)

**Comment by JohannesLichtenberger** [comment]
Currently, after checking with `YourKit` instead of the async profiler it seems the traversal to the ancestors sometimes is costly. I think this is fixable :-)
