### ISSUE TITLE
update to java 11 

### ISSUE THREAD

**Issue by Loki-Afro** [sirixdb/sirix#59]
consider updating  to java 11 

java 9 is EOL ... :)

**Comment by JohannesLichtenberger** [comment]
Thank you, yes will do :-)

**Comment by JohannesLichtenberger** [comment]
Just checked, locally it's running with an updated Mockito, however somehow Travis doesn't build. Maybe it's an issue related to transitive dependencies where Mockito is used somewhere else as a dependency (and it's older) and the order of execution is different on my machine, hm.

**Comment by JohannesLichtenberger** [comment]
Changed to Java 11 / OpenJDK 11, thanks :-)
