### ISSUE TITLE
Correct Name + SVG Logo?

### ISSUE THREAD

**Issue by apavlo** [sirixdb/sirix#61]
I've added your new system to my encyclopedia of databases:

https://dbdb.io/db/sirix

Two questions:

1. Is the official name of the database `Sirix` or `SirixDB`? The Github repo uses both.

2.  Is there an SVG logo available?

-- Andy

**Comment by JohannesLichtenberger** [comment]
Hey, thanks so much. The name is SirixDB :-)

Oh and the core and everything is written in Java, the RESTful API is written in Kotlin.

Yes, I have an SVG logo

**Comment by apavlo** [comment]
Fixed. Thanks!

https://dbdb.io/db/sirixdb

**Comment by JohannesLichtenberger** [comment]
The SVG-logo: https://raw.githubusercontent.com/sirixdb/sirix/master/SVGlogo.svg
