### ISSUE TITLE
Fix Sonarqube workflow

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#615]

**Comment by NusaibaNizam** [comment]
@JohannesLichtenberger , May I know the details?

**Comment by JohannesLichtenberger** [comment]
https://github.com/sirixdb/sirix/actions/workflows/sonarqube.yml

**Comment by JohannesLichtenberger** [comment]
@Aminmalek can you check this one? It's really annoying that it always fails, to say the least ;-)

**Comment by Aminmalek** [comment]
> @Aminmalek can you check this one? It's really annoying that it always fails, to say the least ;-)

yes of course I will work on it.

**Comment by Aminmalek** [comment]
I checked out the last commit I found this:
`
Expiring Daemon due to JVM Metaspace space being exhausted
`

```
Expiring Daemon due to JVM Metaspace space being exhausted
Cannot generate ucfg for file /home/runner/work/sirix/sirix/bundles/sirix-xquery/src/main/java/org/sirix/xquery/compiler/expression/IndexExpr.java for method at line 249
```
`
Error while generating IR for method insert at file /home/runner/work/sirix/sirix/bundles/sirix-xquery/src/main/java/org/sirix/xquery/json/JsonDBObject.java`
```

Error while generating IR for method modify at file /home/runner/work/sirix/sirix/bundles/sirix-xquery/src/main/java/org/sirix/xquery/json/JsonDBObject.java
java.lang.IllegalStateException: Failed to translate expression
```

**Comment by JohannesLichtenberger** [comment]
We have to set something as `-XX:MaxMetaspaceSize=512m` as a JVM flag for the sonarqube build

**Comment by Aminmalek** [comment]
> We have to set something as `-XX:MaxMetaspaceSize=512m` as a JVM flag for the sonarqube build

Yes, it seems there are some problems in code I'm checking it
