### ISSUE TITLE
Error response from daemon: error while creating mount source path '/opt/sirix/sirix-data': mkdir /opt/sirix: read-only file system

### ISSUE THREAD

**Issue by Aminmalek** [sirixdb/sirix#632]
**Describe the bug**
I ran container of keycloack with` sudo docker compose up keycloak` and the then `sudo docker compose up` and I had this error

```
 ✔ Container sirix-keycloak-1  Running                                                                                    0.0s 
Attaching to sirix-keycloak-1, sirix-server-1
Error response from daemon: error while creating mount source path '/opt/sirix/sirix-data': mkdir /opt/sirix: read-only file system
```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
to start the docker container right after

**Additional context**

![Screenshot from 2023-06-25 01-18-34](https://github.com/sirixdb/sirix/assets/76443257/e2c30ae3-4b73-41aa-b20d-8242c694b6f8)

**Comment by JohannesLichtenberger** [comment]
Maybe a suggestion from the answers in https://stackoverflow.com/questions/45764477/docker-compose-error-while-creating-mount-source-path

helps?

**Comment by Aminmalek** [comment]
> Maybe a suggestion from the answers in https://stackoverflow.com/questions/45764477/docker-compose-error-while-creating-mount-source-path
> 
> helps?

it seems that there a problem in docker installed with snap I'm trying to solve it

**Comment by JohannesLichtenberger** [comment]
Let me know... hope you'll get the docker container to run.

**Comment by Aminmalek** [comment]
i fixed this issue with purged docker installed by snap and install the official version
[issue link](https://github.com/docker-snap/docker-snap/issues/146)
