### ISSUE TITLE
docker container keeps restarting

### ISSUE THREAD

**Issue by Aminmalek** [sirixdb/sirix#634]
**Describe the bug**
when I started the docker container its restarting due to an error

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Description of what you expected to happen.

**Additional context**
![pic](https://github.com/sirixdb/sirix/assets/76443257/4067bdb7-91c3-49da-bb7e-521a7839294d)

**Comment by JohannesLichtenberger** [comment]
We'll have to check which other options we have. It's specified in the focker compose file: `restart: always`

**Comment by Aminmalek** [comment]
I think it's related to an error to container in Java app

**Comment by JohannesLichtenberger** [comment]
The restarting on failure seems to be on purpose at least ;-) not sure what's causing your problem. Maybe another server is listening on port 8080?

**Comment by Aminmalek** [comment]
> The restarting on failure seems to be on purpose at least ;-) not sure what's causing your problem. Maybe another server is listening on port 8080?

I will check the port and say the result

**Comment by Aminmalek** [comment]
> > The restarting on failure seems to be on purpose at least ;-) not sure what's causing your problem. Maybe another server is listening on port 8080?
> 
> I will check the port and say the result

The port is free and the keyclaok is running but the server container can't connect to the local host 8080

**Comment by JohannesLichtenberger** [comment]
In the sirix configuration file can you try "host.docker.internal" instead of localhost?

**Comment by Aminmalek** [comment]
> 

it does not fix it, I have this error
`java.net.UnknownHostException: Failed to resolve 'host.docker.internal' [A(1)] after 2 queries `

**Comment by JohannesLichtenberger** [comment]
Can we close this!?

**Comment by Aminmalek** [comment]
> Can we close this!?

Yes I think, can you please run the docker compose in your os to see if there isn't any problem.
