### ISSUE TITLE
Question: Multiple xml documents

### ISSUE THREAD

**Issue by janprill** [sirixdb/sirix#65]
Just a question:

I'm a noob, so bear with me iff the answer is obvious: But I wonder if there is a way to query the database for results from n xml files via a single query. In other words: is this a database providing sophisticated search possibilities over a single document or multiple documents?

**Comment by JohannesLichtenberger** [comment]
Hey, it's possible with the XQuery function `fn:collection()`. In the RESTful API currently you'd have to POST your query to the "/" endpoint, without specifying the database and resource. Then specify the database to open in fn:collection('database').

For instance have a look at https://en.wikibooks.org/wiki/XQuery/Searching_multiple_collections

**Comment by JohannesLichtenberger** [comment]
Hope it helps :-)

**Comment by janprill** [comment]
Thanks Johannes!
