### ISSUE TITLE
Link to an unsecure website in README.md

### ISSUE THREAD

**Issue by parthrc** [sirixdb/sirix#673]
**Describe the bug**
README contains a link to an unsecure website which is a security issue for the visitors.

**To Reproduce**
Click on the first link in the "Keeping all versions of your data by sharing structure" section in the readme.md

**Expected behavior**
The link should point towards a secure website.

**Additional context**
The link should be removed altogether or updated to a working version.

**Comment by Aminmalek** [comment]
you mean this link right?
https://www.hadoop360.datasciencecentral.com/blog/temporal-databases-why-you-should-care-and-how-to-get-started-par

**Comment by parthrc** [comment]
@Aminmalek yes

**Comment by Aminmalek** [comment]
@JohannesLichtenberger

**Comment by JohannesLichtenberger** [comment]
@Aminmalek you can make a PR :-)

**Comment by Aminmalek** [comment]
> @Aminmalek you can make a PR :-)

do you to link to be removed?or something else

**Comment by JohannesLichtenberger** [comment]
Yes, I think that's best for now
