### ISSUE TITLE
Example of JSON document modification, retrieval

### ISSUE THREAD

**Issue by canadaduane** [sirixdb/sirix#78]
Are there any examples of JSON document storage, modification & retrieval? The README covers XML documents well.

**Comment by JohannesLichtenberger** [comment]
Does this help?

https://sirix.io/documentation.html#api-documentation

**Comment by JohannesLichtenberger** [comment]
Or probably 

https://hackernoon.com/asynchronous-temporal-rest-with-vert-x-keycloak-and-kotlin-coroutines-217b25756314?source=friends_link&sk=5eabb36b2984cf61a2dff3f9fe45addc

You could also ask in the community forum: https://sirix.discourse.group/

**Comment by canadaduane** [comment]
This is a good start, thank you!

**Comment by JohannesLichtenberger** [comment]
Feel free to ask anything, but maybe preferrably in the forum :-)
