### ISSUE TITLE
Table component in Vue.js to display revision history metadata

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#83]
For instance to display the author, the ID of the author, the revision number, a revision timestamp and an optional commit comment in each row.

**Comment by JohannesLichtenberger** [comment]
Repository: https://github.com/sirixdb/sirix-web-frontend

**Comment by pareshjoshi** [comment]
@JohannesLichtenberger  how does this differ from the default layout that it has currently?

**Comment by JohannesLichtenberger** [comment]
Ah, yes... it's the starting point I guess :-)
