### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#90]

**Comment by themayurkumbhar** [comment]
Hi @JohannesLichtenberger 
What kind of favicon you are looking for?

**Comment by JohannesLichtenberger** [comment]
Hey, good question, but I don't really like the SirixDB logo, so I guess it's totally up to you... But for https://sirix.io :-)

**Comment by JohannesLichtenberger** [comment]
Hey @karmakaze, would it be possible to get a red version? :-)

**Comment by karmakaze** [comment]
Absolutely. might also try out styling a bit more too.

**Comment by JohannesLichtenberger** [comment]
Cool :-) thanks so much
