### ISSUE TITLE
OAuth2 auhtorization code flow for web applications

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#96]
Provide a configurable mechanism to switch between the authorization methods and implement the authorization code flow in SirixVerticle in the REST API.

**Comment by MrBuggySan** [comment]
I haven't much experience with OAuth2... 
a question though, do you mean letting the user specify their own auth server? and the url of the auth server will be passed in as env variable? 
Also, are we configuring between password credential flow AND authorization code only? or do you see use cases for the other oauth flows as well?

**Comment by JohannesLichtenberger** [comment]
For now I hardcoded Keycloak. The URL is passed via a JSON Vert.x config file.

I think the two flows you mentioned should suffice.

**Comment by MrBuggySan** [comment]
I see.
For configuring the auth server. Do you want that to happen in compile time via config file or during run time via rest api?

**Comment by JohannesLichtenberger** [comment]
Hey, there's a JSON config file for the REST-API, which could simply be queried / to provide the configuration options for the Keycloak authentication via Vert.x.

**Comment by JohannesLichtenberger** [comment]
Have a look into the SirixVerticle class :-)
