### ISSUE TITLE
Websockets to stream resource changes into the client / browser

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#98]
I'd put this into the rest-api module and build it with Vert.x and Kotlin.

**Comment by RushikeshSawant** [comment]
Hi @JohannesLichtenberger I would like to work on this. Could please provide anymore info/suggestions you have on this? And could you please assigns this to me.

**Comment by JohannesLichtenberger** [comment]
Hey, it's all about streaming resource changes directly to a client. For instance as an after commit hook. Might be interesting for dashboards or something like that!?

**Comment by JohannesLichtenberger** [comment]
@RushikeshSawant, should I work on this instead? Thanks nontheless for your interest :)

**Comment by RushikeshSawant** [comment]
Please go ahead and take on this @JohannesLichtenberger. Sorry I am currently caught up with other things.
